titre = "Ecoute la musique de ton groupe de musignons"

select_music = "Quelle était la musique choisie ?"
select_musignon_1 = "Quel est le premier instrument?"
select_musignon_2 = "Quel est le deuxième instrument?"
select_musignon_3 = "Quel est le troisième instrument?"
change_rythm_text = "Effet musignon : change le rythme"
change_height_text = "Effet musignon : change la hauteur"
text_choice = "Choisissez vos musignons"
submit_form = "Crée ta musique!"
download = "Télécharges le résultat!"
name_musique = "ma_musique.mid"
end_creation = "Musique créée, clique sur Télécharger"
form_name = "Choix Musique"